### ISSUE TITLE
where can i find libcas?

### ISSUE THREAD

**Issue by g413164351** [sisl/CCAS.jl#1]
Hi,
where can i find libcas and it contains? such as "parameters/0.8.3.standard.r13.config.txt"
```const LIBCAS_CONFIG = Pkg.dir("CCAS/libcas/parameters/0.8.3.standard.r13.config.txt")```

**Comment by mykelk** [comment]
libcas is not included in this library (as noted in the readme). That library is not publicly available. If you are trying to do some experimentation with collision avoidance, you can check out: https://github.com/sisl/CollisionAvoidancePOMDPs.jl
